publish:
  docker:
    registry:  ec2-52-213-177-144.eu-west-1.compute.amazonaws.com:5000
    username: admin
    password: password
    repo: foo/bar
    tag: latest
    file: Dockerfile
    insecure: false

