pipeline:

  build:
    privileged: true
    image: myJava:latest
    environment:
      - DOCKER_HOST=tcp://$${ARTIFACTORY_DNS}:5000
    commands:
      - docker build -t myJava .
    when:
      branch: master
      event: push

services:
  dind:
    image: myJava:latest
    privileged: true
    command:
      - "-s"
      - "overlay"

publish:
    docker:
        username: $$DOCKER_ARTIFACTORY_USERNAME
        password: $$DOCKER_ARTIFACTORY_PASSWORD
        email: james_forbes@live.co.uk
        repo: privately registry
        tag: latest
        file: Dockerfile
        environment:
          - DOCKER_HOST=tcp://$${ARTIFACTORY_DNS}:5000



image_to_artifactory:
  image: myJava:latest
  environment:
    - DOCKER_HOST=tcp://${ARTIFACTORY_DNS}:5000
  commands:
    - docker login -u="${DOCKER_ARTIFACTORY_USERNAME}" -p=${DOCKER_ARTIFACTORY_PASSWORD} ${ARTIFACTORY_DNS}:5001
    - docker tag myJava ${ARTIFACTORY_DNS}:5001/myJava:${DRONE_COMMIT_SHA}
    - docker push ${ARTIFACTORY_DNS}:5001/myJava:${DRONE_COMMIT_SHA}
  when:
    branch: master
    event: push

