pipeline:

  build:
    privileged: true
    image: myJava:latest
    environment:
      - DOCKER_HOST=tcp://127.0.0.1:2375
    commands:
      - docker build -t myJava .
    when:
      branch: master
      event: push

services:
  dind:
    image: myJava:latest
    privileged: true
    command:
      - "-s"
      - "overlay"

