publish:
  artifactory:
    url: ec2-52-213-177-144.eu-west-1.compute.amazonaws.com:5000
    username: admin
    password: password 
    pom: pom.xml 
    repo_key: libs-snapshot-local
    files: 
      - drone
      - dronefile
