publish:
  docker: 
    registry: ec2-52-213-177-144.eu-west-1.compute.amazonaws.com:5000
    insecure: true
    tag:      latest
    file:     Dockerfile
    username: forbes
    password: pass
    email: james_forbes@live.co.uk
    storage_driver: overlay
