#!/bin/bash
docker login -u="${DOCKER_ARTIFACTORY_USERNAME}" -p=${DOCKER_ARTIFACTORY_PASSWORD} ${ARTIFACTORY_DNS}:5001
docker tag myJava ${ARTIFACTORY_DNS}:5001/myJava:${DRONE_COMMIT_SHA}
docker push ${ARTIFACTORY_DNS}:5001/myJava:${DRONE_COMMIT_SHA}

